# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
    - JVM_OPTS: -Xmx3200m
    - TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: gradle dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle build
    - run: ./gradlew sonarqube -Dsonar.projectKey=marcinnidecki
        -Dsonar.organization=MarcinNidecki_car-door-web-service -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=c97b0ffac764c6c40cdc9e52ba6382d3c9bf939f
workflows:
  version: 2
  workflow:
    jobs:
    - build
    
=
